-- AlterTable
ALTER TABLE `attendances` MODIFY `status` ENUM('PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE', 'WORK_FROM_HOME', 'HOLIDAY', 'WEEK_OFF', 'OUTDOOR_DUTY', 'COMPENSATORY_OFF', 'PERMISSION', 'WORK_ON_HOLIDAY', 'CL', 'SL', 'EL', 'LOP') NOT NULL DEFAULT 'PRESENT';
