-- AlterTable
ALTER TABLE `employee_documents` MODIFY `type` ENUM('RESUME', 'OFFER_LETTER', 'APPOINTMENT_LETTER', 'ID_PROOF', 'ADDRESS_PROOF', 'EDUCATIONAL_CERTIFICATE', 'EXPERIENCE_CERTIFICATE', 'RELIEVING_LETTER', 'SALARY_CERTIFICATE', 'OTHER') NOT NULL;
